### ISSUE TITLE
登录的核心

### ISSUE THREAD

**Issue by Atomseek** [Welllee12366/GXNUDiagSystem#1]
小弟研究了大半天，终于才发现，大佬是发送一个post请求实现认证的。

**Comment by Welllee12366** [comment]
有一个GET接口。你仔细分析那个web登录接口就能发现。

**Comment by Atomseek** [comment]
> 
> 
> 有一个GET接口。你仔细分析那个web登录接口就能发现。

小弟学识尚浅，并不懂网络分析。都是按网上教程依葫芦画瓢，记录登录时候的请求改写成curl而已，望大佬指点。

**Comment by Welllee12366** [comment]
抓出get接口->构造url请求->curl url请求
